.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH libtree 1 "2020-04-13" Linux "User Manuals"
.SH NAME
libtree \- print shared object dependencies as a tree
.SH SYNOPSIS
.B libtree 
[
.I option
]... [
.I file
]...
.SH DESCRIPTION
.B libtree
prints the shared libraries required by each program or shared library on the command line as a tree, and optionally copies them over to a directory. By default certain common system libraries are not shown to prune the tree.
.SH OPTIONS
.IP "-h, --help"
Print usage
.IP "--version"
Print version info
.IP "-p, --path"
Show the path of libraries instead of their 
.B soname
.IP "-v, --verbose"
Show the skipped libraries without their children
.IP "-a, --all"
Show the skipped libraries and their children
.IP "-l, --ldconf arg"
Path to custom
.I ld.so.conf
file
.IP "-s, --skip \fIlib\fI"
Mark the shared library library
.I lib
as skipped
.IP "--platform arg"
Expand
.I $PLATFORM
in rpaths as
.I arg
instead of the default value from
.B AT_PLATFORM
.IP "-d, --destination \fIpath\fI"
Copy all executables and shared libraries over to a directory
.I path
.IP --strip
Call strip on executables and shared libraries that are copied
.IP --chrpath
Call chrpath on executables and shared libraries that are copied
.SH AUTHOR
Harmen Stoppels <me@harmenstoppels.nl>
.SH "SEE ALSO"
.BR ldd (1)

